name: portfolio_main
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/Moiz Baloch 11.png
    - Assets/Moiz Baloch 22.png
    - Assets/Moiz Baloch 33.png
    - Assets/Moiz Baloch.jpg
